apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: neocare

spec:
  replicas: 4

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      serviceAccountName: aws-csi-secret-manager

      containers:
        - name: backend
          image: 347026173735.dkr.ecr.us-east-1.amazonaws.com/neocare-backend:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret

          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets"
              readOnly: true

      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "neocare-secrets"