apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: neocare
type: Opaque
stringData:
  DB_PASSWORD: "952004"
  JWT_SECRET: "neocare_jwt_2025_secure_key_@123"
  EMAIL_PASS: "badk kgyr ezku fwxa"