sonar.projectKey=NEOCARE
sonar.projectName=NEOCARE
sonar.projectVersion=1.0

# Scan the React frontend
sonar.sources=frontend/src

# Ignore generated folders
sonar.exclusions=**/node_modules/**,**/dist/**

sonar.sourceEncoding=UTF-8