apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: neocare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: neocare-frontend-deploy
        image: 347026173735.dkr.ecr.us-east-1.amazonaws.com/neocare-frontend:latest
        ports:
        - containerPort: 8080
