apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: neocare-secrets
  namespace: neocare
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "dev/postgres"
        objectType: "secretsmanager"
        jmesPath:
          - path: "DB_HOST"
            objectAlias: "DB_HOST"
          - path: "DB_PASSWORD"
            objectAlias: "DB_PASSWORD"
          - path: "JWT_SECRET"
            objectAlias: "JWT_SECRET"
          - path: "EMAIL_PASS"
            objectAlias: "EMAIL_PASS"
  secretObjects:
  - secretName: backend-secret
    type: Opaque
    data:
    - key: DB_HOST
      objectName: DB_HOST
    - key: DB_PASSWORD
      objectName: DB_PASSWORD
    - key: JWT_SECRET
      objectName: JWT_SECRET
    - key: EMAIL_PASS
      objectName: EMAIL_PASS