apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: neocare-secrets
  namespace: neocare

spec:
  provider: aws

  parameters:
    objects: |
      - objectName: "dev/postgres"
        objectType: "secretsmanager"

  secretObjects:
    - secretName: backend-secret
      type: Opaque
      data:
        - objectName: DB_HOST
          key: DB_HOST
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
        - objectName: JWT_SECRET
          key: JWT_SECRET
        - objectName: EMAIL_PASS
          key: EMAIL_PASS
        